--CREATING WAREHOUSES
-- Warehouse for data ingestion (Bronze layer ETL)
CREATE OR REPLACE WAREHOUSE INGEST_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for raw data ingestion into Bronze layer';

-- Warehouse for data transformation (Silver layer processing)
CREATE OR REPLACE WAREHOUSE TRANSFORM_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for data transformation and cleansing';

-- Warehouse for reporting and analytics (Gold layer queries)
CREATE OR REPLACE WAREHOUSE REPORTING_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for reporting and BI workloads';

-- Warehouse for data science and ML workloads (Platinum layer)
CREATE OR REPLACE WAREHOUSE ANALYTICS_WH
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for data science and ML workloads';


--GRANTING PRIVILES ON WAREHOUSE TO ROLES
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE INGEST_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE REPORTING_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYST_ROLE;

-- Data Engineer gets access to ingestion and transformation warehouses
GRANT USAGE, OPERATE ON WAREHOUSE INGEST_WH TO ROLE DATA_ENG_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENG_ROLE;

-- Admin gets full control on all warehouses
GRANT ALL PRIVILEGES ON WAREHOUSE INGEST_WH TO ROLE ADMIN_ROLE;
GRANT ALL PRIVILEGES ON WAREHOUSE TRANSFORM_WH TO ROLE ADMIN_ROLE;
GRANT ALL PRIVILEGES ON WAREHOUSE REPORTING_WH TO ROLE ADMIN_ROLE;
GRANT ALL PRIVILEGES ON WAREHOUSE ANALYTICS_WH TO ROLE ADMIN_ROLE;

-- Verification
SHOW WAREHOUSES LIKE '%_WH';


SHOW RESOURCE MONITORS;

